- name: create backup configuration ({{_profile.key}}
  template:
    src: backup-profile.conf.j2
    dest: "{{_backup_profile_dir}}/{{_profile.key}}"

- name: create exclude configuration ({{_profile.key}}
  template:
    src: exclude.conf.j2
    dest: "{{_backup_exclude_dir}}/{{_profile.key}}.excludes"
  when: _profile.value.excludes is defined

# create profile secrets. we load global secrets first, and then profile secrets, and then export stuff
- name: create secrets configuration ({{_profile.key}}
  template:
    src: secrets.conf.j2
    dest: "{{_backup_secret_dir}}/{{_profile.key}}.secrets"
    mode: 0600
  when: _profile.value.secrets is defined

- name: create profile timer ({{_profile.key}}
  include_role:
    name: basic-host
    tasks_from: add_timer
  when: _profile.value.oncalendar is defined
  vars:
    systemd_timer_oncalendar: "{{_profile.value.oncalendar}}"
    systemd_timer_name: "backup@{{_profile.key}}"
    systemd_timer_add_service: False
