- name: remove backup configuration
  file:
    path: "{{_backup_profile_dir}}/{{_profile.key}}"
    state: absent

- name: create exclude configuration
  file:
    path: "{{_backup_exclude_dir}}/{{_profile.key}}.excludes"
    state: absent
  when: _profile.value.excludes is defined

- name: remove SSH config for rclone_ssh transport ({{_profile.key}})
  file:
    path: "{{_backup_lib_dir}}/ssh/{{_profile.key}}.conf"
    state: absent
  when: _profile.value.restic_transport is defined and _profile.value.restic_transport == 'rclone_ssh'

- name: remove profile timer
  include_role:
    name: basic-host
    tasks_from: remove_timer
  when: _profile.value.oncalendar is defined
  vars:
    systemd_timer_name: "backup@{{_profile.key}}"
